version: "2"

services:

  picocms:
    restart: always
    build: .
    image: gprevost/picocms
    command:
      "/run.sh"
    ports:
      - 80:80
    volumes:
#      - ./config:/home/sites/picocms/config
#      - ./content:/home/sites/picocms/content
#      - ./plugins:/home/sites/picocms/plugins
#      - ./themes:/home/sites/picocms/themes
      - ./:/home/sites/picocms
    networks:
      - picocms

networks:
  picocms:
    driver: bridge
